name: Deploy VPC to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'vpc-subnets.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Asegúrate de que esta región coincida con tu cuenta AWS

      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://vpc-subnets.yaml

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file vpc-subnets.yaml \
            --stack-name ClouxterVPCStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
