name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'vpc-subnets.yaml'
      - 'ec2-instances.yaml'
      - 'dynamodb-table.yaml'
      - 's3-bucket.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate VPC Template
        run: |
          aws cloudformation validate-template --template-body file://vpc-subnets.yaml

      - name: Deploy VPC Stack
        run: |
          aws cloudformation deploy \
            --template-file vpc-subnets.yaml \
            --stack-name ClouxterVPCStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Validate EC2 Template
        run: |
          aws cloudformation validate-template --template-body file://ec2-instances.yaml

      - name: Deploy EC2 Stack
        run: |
          aws cloudformation deploy \
            --template-file ec2-instances.yaml \
            --stack-name ClouxterEC2Stack \
            --parameter-overrides VpcId=$(aws cloudformation describe-stacks --stack-name ClouxterVPCStack --query 'Stacks[0].Outputs[?OutputKey==`VpcId`].OutputValue' --output text) PublicSubnet1Id=$(aws cloudformation describe-stacks --stack-name ClouxterVPCStack --query 'Stacks[0].Outputs[?OutputKey==`PublicSubnet1Id`].OutputValue' --output text) PublicSubnet2Id=$(aws cloudformation describe-stacks --stack-name ClouxterVPCStack --query 'Stacks[0].Outputs[?OutputKey==`PublicSubnet2Id`].OutputValue' --output text) \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Validate DynamoDB Template
        run: |
          aws cloudformation validate-template --template-body file://dynamodb-table.yaml

      - name: Deploy DynamoDB Stack
        run: |
          aws cloudformation deploy \
            --template-file dynamodb-table.yaml \
            --stack-name ClouxterDynamoDBStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Validate S3 Template
        run: |
          aws cloudformation validate-template --template-body file://s3-bucket.yaml

      - name: Deploy S3 Stack
        run: |
          aws cloudformation deploy \
            --template-file s3-bucket.yaml \
            --stack-name ClouxterS3Stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
